llm:
  openai:
    provider: "openai"
    model_name: "o4-mini"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
  gemini:
    provider: "gemini"
    model_name: "gemini-1.5-flash"